#! /bin/bash
#SBATCH --job-name="0_C1"
#SBATCH --output="output.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem-per-cpu=8G
#SBATCH --account="mit136"
#SBATCH --export=ALL
#SBATCH -t 24:00:00

source activate molSimplify
python optimize_ANN_C1.py